In [27]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from scipy import interpolate
import os

In [25]:
from pathlib import Path

def root_path() -> Path:
    return Path(os.path.abspath('')).parent.parent.parent 

In [26]:
PATH_DATA = os.path.join(root_path(), 'data\\regions')
PATH_DATA

'c:\\Users\\santa\\Desktop\\Population\\data\\regions'

In [32]:
FILE_NAME_CVS: list[str] = os.listdir(PATH_DATA)
FILE_NAME_PATH_CVS = list(map(lambda file_name: f"{PATH_DATA}\{file_name}", FILE_NAME_CVS))
FILE_NAME_PATH_CVS

['c:\\Users\\santa\\Desktop\\Population\\data\\regions\\Алтайский край.csv',
 'c:\\Users\\santa\\Desktop\\Population\\data\\regions\\Амурская область.csv',
 'c:\\Users\\santa\\Desktop\\Population\\data\\regions\\Астраханская область.csv',
 'c:\\Users\\santa\\Desktop\\Population\\data\\regions\\Белгородская область.csv',
 'c:\\Users\\santa\\Desktop\\Population\\data\\regions\\Брянская область.csv',
 'c:\\Users\\santa\\Desktop\\Population\\data\\regions\\Владимирская область.csv',
 'c:\\Users\\santa\\Desktop\\Population\\data\\regions\\Волгоградская область.csv',
 'c:\\Users\\santa\\Desktop\\Population\\data\\regions\\Вологодская область.csv',
 'c:\\Users\\santa\\Desktop\\Population\\data\\regions\\Воронежская область.csv',
 'c:\\Users\\santa\\Desktop\\Population\\data\\regions\\Дальневосточный федеральный округ.csv',
 'c:\\Users\\santa\\Desktop\\Population\\data\\regions\\Еврейская автономная область.csv',
 'c:\\Users\\santa\\Desktop\\Population\\data\\regions\\Забайкальский край.csv',


In [28]:
#Библиотечная экстраполяция - готово
data = pd.read_csv(PATH_DATA + '\Брянская область.csv',
                   index_col="Age", sep=";")
x = np.array(data.columns)
x = list(map(int, x))
xnew = np.arange(2023, 2027)
tmp = len(data.values[0])
for i in range(0, len(data.index)):
    y = np.array(data.values[i, 0:tmp])
    f = interpolate.interp1d(x, y, fill_value='extrapolate')
    ynew = f(xnew)
    for t in range(0, len(xnew)):
        if (ynew[t] < 0):
            ynew[t] = 0
        data.at[i, xnew[t]] = ynew[t]
data


2009   2010   2012   2013   2014   2015   2016   2017   2018   2019  \
Age                                                                         
0    14157  14332  13793  14384  13755  13547  13975  13262  11441  11046   
1    13234  14158  13474  13783  14343  13681  13537  13875  13155  11375   
2    11966  13239  14315  13404  13734  14294  13631  13460  13776  12998   
3    11823  11982  14242  14257  13317  13669  14182  13546  13321  13599   
4    12259  11847  13360  14216  14206  13253  13652  14195  13541  13262   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
76   10227   7171   8203  10305  11019  10742  10213   9127   8658   6030   
77    8559   9517   5519   7701   9678  10392  10104   9634   8647   8208   
78   11620   7894   6304   5181   7170   9082   9722   9512   9040   8118   
79    9123  10765   7752   5827   4830   6730   8435   8998   8858   8413   
80   59833  63529  67602  69521  69907  68985  70561  71704  73788  74813   

      2020   2021   2022     2023     2024     2025     2026  
Age                                                           
0     9906   9460   8958   8456.0   7954.0   7452.0   6950.0  
1    10977   9831   9423   9015.0   8607.0   8199.0   7791.0  
2    11324  10931   9802   8673.0   7544.0   6415.0   5286.0  
3    12895  11280  10921  10562.0  10203.0   9844.0   9485.0  
4    13587  12944  11260   9576.0   7892.0   6208.0   4524.0  
..     ...    ...    ...      ...      ...      ...      ...  
76    3805   4032   3864   3696.0   3528.0   3360.0   3192.0  
77    5728   3592   3715   3838.0   3961.0   4084.0   4207.0  
78    7763   5367   3318   1269.0      0.0      0.0      0.0  
79    7666   7174   4885   2596.0    307.0      0.0      0.0  
80   75242  75116  73642  72168.0  70694.0  69220.0  67746.0  

[81 rows x 17 columns]

In [36]:
# Проверка точности метода выше на известных данных
data = pd.read_csv(PATH_DATA + '\Брянская область.csv',
                   index_col="Age", sep=";")
x = np.array(data.columns)
x = list(map(int, x))
for n in range(0, 3):
    x = np.delete(x, 10, 0)
xnew = np.arange(2020, 2023)
tmp = len(x)
for i in range(0, len(data.index)):
    ytot = np.array(data.values[i])
    y = np.array(data.values[i, 0:tmp])
    f = interpolate.interp1d(x, y, fill_value='extrapolate')
    ynew = y
    ynew2 = f(xnew)
    ynew = np.append(ynew, ynew2)
    print((1-ytot/ynew)*100)


[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         6.99464839 7.76131045
 9.15728628]
[  0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
 -14.40333507 -25.79654511 -56.13918807]
[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         7.33224223 4.46600245
 8.08327082]
[ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          7.07645745 20.31084422
 24.33312548]
[ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.         -4.65223754 -1.88916877
  9.37625755]
[  0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
  -2.88715953 -11.59836066 -11.91341991]
[ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0

In [37]:
# МНК - в процессе
data = pd.read_csv(PATH_DATA + '\Брянская область.csv',
                   index_col="Age", sep=";")
x = np.array(data.columns)
x = np.array(list(map(int, x)))
x = x-2009
xnew = np.arange(2023, 2027)-2009
tmp = len(data.values[0])
y = np.array(data.values[0])
n = 5
matrixX = [[0]*n for i in range(len(x))]
for i in range(0, len(x)):
    for j in range(0, n):
        matrixX[i][j] = x[i]**j
y = np.array(data.values[0])
matrixX = np.array(matrixX)
print(matrixX)
A = y.dot(matrixX)
print(A)
ynew = A[0]
for a in range(1, n):
    ynew += A[a]*(14**a)
print(ynew)


[[    1     0     0     0     0]
 [    1     1     1     1     1]
 [    1     3     9    27    81]
 [    1     4    16    64   256]
 [    1     5    25   125   625]
 [    1     6    36   216  1296]
 [    1     7    49   343  2401]
 [    1     8    64   512  4096]
 [    1     9    81   729  6561]
 [    1    10   100  1000 10000]
 [    1    11   121  1331 14641]
 [    1    12   144  1728 20736]
 [    1    13   169  2197 28561]]
[   162016   1019594   8839812  86135396 901412928]
34866781608156
